GET  http://localhost:3001/users


###
GET http://localhost:3001/users/EcVrlZ8d989orTthtsPD

###

POST  http://localhost:3001/users
Content-Type: application/json

{
    "status":"Admin",  
}
###
PUT http://localhost:3001/users/EcVrlZ8d989orTthtsPD
Content-Type: application/json

{
    "status":"Pasien",
  
}

###
DELETE http://localhost:3001/users/PVGztgMofoXFxCHYlUGO

